package interfaz;

import business.Person;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;

/**
 * Clase DisplayJPanel: está clase se utiliza para la interfaz de visualización
 * de los perfiles
 * 
 * @author Alan McLure Alarcón
 * @version 21/03/2023
 */
public class DisplayJPanel extends javax.swing.JPanel {

	/**
	 * Constructor: Crea un nuevo formulario DisplayJPanel
	 * 
	 * @param lista     (tipo List) que guarda la lista de personas
	 * @param numPerfil (tipo int) que guarda el número del perfil
	 */
	public DisplayJPanel(List<Person> lista, int numPerfil) {
		initComponents();
		displayPerson(lista, numPerfil);
	}

	/**
	 * Función que muestra los datos del perfil de la persona con los valores de los
	 * datos en la lista en la posición del número de perfil
	 * 
	 * @param lista     (tipo List) que guarda la lista de personas
	 * @param numPerfil (tipo int) que guarda el número del perfil
	 */
	public void displayPerson(List<Person> lista, int numPerfil) {

		textFieldNombre.setText(lista.get(numPerfil).getNombre());
		textFieldEmail.setText(lista.get(numPerfil).getEmail());
		textFieldSeguridadSocial.setText(lista.get(numPerfil).getNumeroSS());
		textFieldFechaNacimiento.setText(lista.get(numPerfil).getFechaNacimiento());
		textFieldPais.setText(lista.get(numPerfil).getPais());
		textFieldCuentaBancaria.setText(lista.get(numPerfil).getNumCuentaBancaria());
		textFieldTelefono.setText(lista.get(numPerfil).getTelefono());
		textFieldDepartamento.setText(lista.get(numPerfil).getDepartamento());
		lblCodigo.setText(lista.get(numPerfil).getCodigo());
		textFieldFechaIncorporacion.setText(lista.get(numPerfil).getFechaIncorporacion());
		textFieldSueldo.setText(String.valueOf(lista.get(numPerfil).getSueldo()));

		String imageTxt = lista.get(numPerfil).getImagetxt();

		try {
			BufferedImage img = ImageIO.read(new File(imageTxt));

			lblImagen.setBounds(100, 100, 280, 250);

			Image dimg = img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
			ImageIcon icon = new ImageIcon(dimg);

			lblImagen.setIcon(icon);
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "Error al cargar la imagen");
		}

	}

	/**
	 * La función inicia los componentes
	 */
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblImagen = new javax.swing.JLabel();
		lblPerfil = new javax.swing.JLabel();
		lblNombre = new javax.swing.JLabel();
		lblPais = new javax.swing.JLabel();
		lblFechaNacimiento = new javax.swing.JLabel();
		lblTelefono = new javax.swing.JLabel();
		lblEmail = new javax.swing.JLabel();
		lblSeguridadSocial = new javax.swing.JLabel();
		lblCuentaBancaria = new javax.swing.JLabel();
		lblCodigoEmpleado = new javax.swing.JLabel();
		lblCodigo = new javax.swing.JLabel();
		lblFechaIncorporacion = new javax.swing.JLabel();
		lblDepartamento = new javax.swing.JLabel();
		lblSueldo = new javax.swing.JLabel();
		textFieldFechaNacimiento = new javax.swing.JTextField();
		textFieldCuentaBancaria = new javax.swing.JTextField();
		textFieldSeguridadSocial = new javax.swing.JTextField();
		textFieldEmail = new javax.swing.JTextField();
		textFieldTelefono = new javax.swing.JTextField();
		textFieldPais = new javax.swing.JTextField();
		textFieldNombre = new javax.swing.JTextField();
		textFieldFechaIncorporacion = new javax.swing.JTextField();
		textFieldDepartamento = new javax.swing.JTextField();
		textFieldSueldo = new javax.swing.JTextField();

		lblImagen.setBackground(new java.awt.Color(102, 102, 102));
		lblImagen.setOpaque(true);

		lblPerfil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		lblPerfil.setText("Perfil");

		lblNombre.setText("Nombre: ");
		lblPais.setText("País: ");
		lblFechaNacimiento.setText("Fecha de nacimiento: ");
		lblTelefono.setText("Teléfono: ");
		lblEmail.setText("Email: ");
		lblSeguridadSocial.setText("Número SS: ");
		lblCuentaBancaria.setText("Número de cuenta bancaria: ");
		lblCodigoEmpleado.setText("Código empleado: ");
		lblDepartamento.setText("Departamento: ");
		lblFechaIncorporacion.setText("Fecha incorporación: ");
		lblSueldo.setText("Sueldo: ");

		textFieldCuentaBancaria.setEditable(false);
		textFieldSeguridadSocial.setEditable(false);
		textFieldEmail.setEditable(false);
		textFieldTelefono.setEditable(false);
		textFieldPais.setEditable(false);
		textFieldFechaNacimiento.setEditable(false);
		textFieldNombre.setEditable(false);
		textFieldDepartamento.setEditable(false);
		textFieldFechaIncorporacion.setEditable(false);
		textFieldSueldo.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(64)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
											.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
													.addComponent(lblSeguridadSocial)
													.addPreferredGap(ComponentPlacement.RELATED, 119, Short.MAX_VALUE))
												.addComponent(lblCuentaBancaria)
												.addComponent(lblSueldo)
												.addComponent(lblFechaIncorporacion)
												.addComponent(lblDepartamento))
											.addPreferredGap(ComponentPlacement.RELATED)
											.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(textFieldSueldo)
												.addComponent(textFieldCuentaBancaria, 244, 244, Short.MAX_VALUE)
												.addGroup(Alignment.TRAILING, layout.createParallelGroup(Alignment.LEADING, false)
													.addComponent(textFieldDepartamento, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
													.addComponent(textFieldSeguridadSocial, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
												.addComponent(textFieldFechaIncorporacion, 244, 244, Short.MAX_VALUE)))
										.addGroup(layout.createSequentialGroup()
											.addComponent(lblEmail)
											.addPreferredGap(ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
											.addComponent(textFieldEmail, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)))
									.addPreferredGap(ComponentPlacement.RELATED))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblTelefono)
									.addPreferredGap(ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
									.addComponent(textFieldTelefono, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblFechaNacimiento)
									.addPreferredGap(ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
									.addComponent(textFieldFechaNacimiento, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(lblNombre)
										.addComponent(lblCodigoEmpleado)
										.addComponent(lblPais))
									.addPreferredGap(ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(textFieldPais, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
										.addComponent(lblCodigo)
										.addComponent(textFieldNombre, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)))))
						.addGroup(layout.createSequentialGroup()
							.addContainerGap(301, Short.MAX_VALUE)
							.addComponent(lblPerfil, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE)))
					.addGap(69)
					.addComponent(lblImagen, GroupLayout.PREFERRED_SIZE, 274, GroupLayout.PREFERRED_SIZE)
					.addGap(260))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(74)
					.addComponent(lblPerfil)
					.addGap(68)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblCodigoEmpleado)
								.addComponent(lblCodigo))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblNombre)
								.addComponent(textFieldNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblPais)
									.addGap(14))
								.addGroup(layout.createSequentialGroup()
									.addComponent(textFieldPais, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.UNRELATED)))
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(textFieldFechaNacimiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblFechaNacimiento))
							.addGap(12)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblTelefono)
								.addComponent(textFieldTelefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(12)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(textFieldEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblEmail))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblSeguridadSocial)
								.addComponent(textFieldSeguridadSocial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(13)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(textFieldCuentaBancaria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCuentaBancaria))
							.addGap(13)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(textFieldFechaIncorporacion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblFechaIncorporacion))
							.addPreferredGap(ComponentPlacement.RELATED))
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblImagen, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
							.addGap(36)))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(textFieldDepartamento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblDepartamento))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblSueldo)
						.addComponent(textFieldSueldo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(37, Short.MAX_VALUE))
		);
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

//	private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextFieldActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_emailTextFieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lblPerfil;
	private javax.swing.JLabel lblCodigoEmpleado;
	private javax.swing.JLabel lblCodigo;
	private javax.swing.JLabel lblNombre;
	private javax.swing.JLabel lblPais;
	private javax.swing.JLabel lblFechaNacimiento;
	private javax.swing.JLabel lblTelefono;
	private javax.swing.JLabel lblEmail;
	private javax.swing.JLabel lblSeguridadSocial;
	private javax.swing.JLabel lblCuentaBancaria;
	private javax.swing.JLabel lblFechaIncorporacion;
	private javax.swing.JLabel lblDepartamento;
	private javax.swing.JLabel lblImagen;
	private javax.swing.JLabel lblSueldo;
	private javax.swing.JTextField textFieldNombre;
	private javax.swing.JTextField textFieldPais;
	private javax.swing.JTextField textFieldFechaNacimiento;
	private javax.swing.JTextField textFieldTelefono;
	private javax.swing.JTextField textFieldEmail;
	private javax.swing.JTextField textFieldSeguridadSocial;
	private javax.swing.JTextField textFieldCuentaBancaria;
	private javax.swing.JTextField textFieldFechaIncorporacion;
	private javax.swing.JTextField textFieldDepartamento;
	private javax.swing.JTextField textFieldSueldo;
}
